name: CI with MLflow

on: [push]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python v3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5

      - name: Install Library
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pipeline
        run: |
          python pipeline.py diamonds-price.arff \
           --target-col price \
           --outlier-treshold 1.5
        working-directory: preprocessing/

      - name: Save Preprocessor
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: |
            joblibs/*
            !.gitkeep

      - name: Save Preprocessed Data
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed_data
          path: |
            dataset/preprocessed/diamonds-price.csv

  integrate:
    env:
      DOCKER_IMAGENAME: gibrandaffa/submission-mlflow-docker

    runs-on: ubuntu-latest
    needs: preprocess
    environment: docker

    steps:
      - uses: actions/checkout@v4

      - name: Download Preprocessed Data
        uses: actions/download-artifact@v4
        with:
          name: preprocessed_data
          path: dataset/preprocessed/

      - name: Setup Python v3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5

      - name: Install Library
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the Model
        run: |
          mlflow run --env-manager=local train

      - name: Get Run ID
        run: |
          RUN_ID=$(ls -td mlruns/0/* | head -n 1 | cut -d '/' -f 3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID: $RUN_ID"

      - name: Build Docker
        run: |
          mlflow models build-docker -m "runs:/$RUN_ID/model" --name $DOCKER_IMAGENAME:1

      - name: Log In to Docker Account
        uses: docker/login-action@v2
        with:
          username: gibrandaffa
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGENAME:1