name: Data Preprocessing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python v3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      
      - name: Install Library
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pipeline
        run: |
          python pipeline.py diamonds-price.arff \
            --target-col price \
            --outlier-treshold 1.6
        working-directory: preprocessing/

      - name: Save Preprocessor
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: |
            joblibs/*
            !.gitkeep

      - name: Save Preprocessed Data
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed_data
          path: |
            dataset/preprocessed/diamonds-price.csv